export const TIMELINE_OPTIONS = [
  { value: "1-2_weeks", label: "1 – 2 Weeks" },
  { value: "2-3_weeks", label: "2 – 3 Weeks" },
  { value: "3-4_weeks", label: "3 – 4 Weeks" },
  { value: "1_month", label: "1 Month" },
  { value: "1-2_months", label: "1 – 2 Months" },
  { value: "2-3_months", label: "2 – 3 Months" },
  { value: "3+_months", label: "3+ Months" },
];

export const UNIT_OPTIONS = [
  { value: "ft", label: "ft" },
  { value: "m", label: "m" },
];

export const SERVICE_PRESETS = {
  CONCEPT: [
    { value: "2D Space Planning", label: "2D Space Planning" },
    { value: "3D Photorealistic Renders", label: "3D Photorealistic Renders" },
    { value: "Moodboard & Color Palette", label: "Moodboard & Color Palette" },
  ],
  CONTRACTOR_READY: [
    { value: "2D Space Planning", label: "2D Space Planning" },
    { value: "3D Photorealistic Renders", label: "3D Photorealistic Renders" },
    { value: "Electrical & Lighting Layout", label: "Electrical & Lighting Layout" },
    { value: "Plumbing & Sanitary Layout", label: "Plumbing & Sanitary Layout" },
    { value: "Reflected Ceiling Plan (RCP)", label: "Reflected Ceiling Plan (RCP)" },
    { value: "Carpentry & Wardrobe Elevations", label: "Carpentry & Wardrobe Elevations" },
    { value: "Bill of Quantities (BOQ)", label: "Bill of Quantities (BOQ)" },
  ],
}
export const MATERIAL_OPTIONS = [
  { value: "Teak Wood", label: "Teak Wood" },
  { value: "Anjili Wood", label: "Anjili Wood" },
  { value: "Mahogany", label: "Mahogany" },
  { value: "Jackfruit Wood (Plavu)", label: "Jackfruit Wood (Plavu)" },
  { value: "Rosewood (Eeti)", label: "Rosewood (Eeti)" },
  { value: "Walnut Wood", label: "Walnut Wood" },
  { value: "White Oak", label: "White Oak" },
  { value: "Sheesham Wood", label: "Sheesham Wood" },
  { value: "Ash Wood", label: "Ash Wood" },
  { value: "Pinewood", label: "Pinewood" },
  { value: "BWP Marine Plywood", label: "BWP Marine Plywood" },
  { value: "HDHMR Board", label: "HDHMR Board" },
  { value: "MDF Board", label: "MDF Board" },
  { value: "WPC Board", label: "WPC Board" },
  { value: "Birch Plywood", label: "Birch Plywood" },

  { value: "Laminate", label: "Laminate" },
  { value: "Matte Laminate", label: "Matte Laminate" },
  { value: "High-Gloss Laminate", label: "High-Gloss Laminate" },
  { value: "Veneer", label: "Veneer" },
  { value: "Acrylic Sheet", label: "Acrylic Sheet" },
  { value: "PU Finish", label: "PU Finish" },
  { value: "Duco Paint", label: "Duco Paint" },
  { value: "Fluted Charcoal Panels", label: "Fluted Charcoal Panels" },
  { value: "WPC Fluted Louvers", label: "WPC Fluted Louvers" },
  { value: "Fluted MDF Panels", label: "Fluted MDF Panels" },
  { value: "Acoustic Wall Panels", label: "Acoustic Wall Panels" },

  { value: "Italian Marble", label: "Italian Marble" },
  { value: "Indian Marble", label: "Indian Marble" },
  { value: "Granite", label: "Granite" },
  { value: "Engineered Quartz", label: "Engineered Quartz" },
  { value: "Sintered Stone", label: "Sintered Stone" },
  { value: "Travertine", label: "Travertine" },
  { value: "Terrazzo", label: "Terrazzo" },
  { value: "Onyx Stone", label: "Onyx Stone" },
  { value: "Corian Solid Surface", label: "Corian Solid Surface" },
  { value: "Nano White Glass", label: "Nano White Glass" },
  { value: "Kota Stone", label: "Kota Stone" },
  { value: "Laterite Stone Cladding", label: "Laterite Stone Cladding" },
  { value: "Terracotta Tiles", label: "Terracotta Tiles" },
  { value: "Red Oxide Finish", label: "Red Oxide Finish" },
  { value: "Vitrified / Ceramic Tiles", label: "Vitrified / Ceramic Tiles" },

  { value: "Clear Toughened Glass", label: "Clear Toughened Glass" },
  { value: "Fluted / Reeded Glass", label: "Fluted / Reeded Glass" },
  { value: "Tinted Glass (Bronze / Grey)", label: "Tinted Glass (Bronze / Grey)" },
  { value: "Frosted Glass", label: "Frosted Glass" },
  { value: "Lacquered Glass", label: "Lacquered Glass" },
  { value: "Antique Mirror", label: "Antique Mirror" },
  { value: "LED Backlit Mirror", label: "LED Backlit Mirror" },

  { value: "Brushed Brass / Gold PVD", label: "Brushed Brass / Gold PVD" },
  { value: "Rose Gold PVD Steel", label: "Rose Gold PVD Steel" },
  { value: "Matte Black Metal", label: "Matte Black Metal" },
  { value: "Anodized Aluminum Profile", label: "Anodized Aluminum Profile" },
  { value: "Wrought Iron", label: "Wrought Iron" },
  { value: "Stainless Steel (SS 304)", label: "Stainless Steel (SS 304)" },
  { value: "Copper Accent Metal", label: "Copper Accent Metal" },

  { value: "Venetian Plaster", label: "Venetian Plaster" },
  { value: "Limewash Finish", label: "Limewash Finish" },
  { value: "Microcement", label: "Microcement" },
  { value: "Textured Wallpaper", label: "Textured Wallpaper" },
  { value: "Exposed Brick Cladding", label: "Exposed Brick Cladding" },
  { value: "CNC Cut Jali Panels", label: "CNC Cut Jali Panels" },

  { value: "Cane / Rattan", label: "Cane / Rattan" },
  { value: "Jute Mesh", label: "Jute Mesh" },
  { value: "Bouclé Fabric", label: "Bouclé Fabric" },
  { value: "Velvet", label: "Velvet" },
  { value: "Natural Linen", label: "Natural Linen" },
  { value: "Cotton Fabric Upholstery", label: "Cotton Fabric Upholstery" },
  { value: "Genuine Leather", label: "Genuine Leather" },
  { value: "Leatherette", label: "Leatherette" },
];
