export const SORT_OPTIONS = [
    { label: "A → Z", value: "az" },
    { label: "Z → A", value: "za" },
    { label: "Budget: Low → High", value: "price_asc" },
    { label: "Budget: High → Low", value: "price_desc" },
];

export const SPACE_TYPE_AI = [
    "Living Room",
    "Drawing Room",
    "Dining Room",
    "Family Room",
    "Lounge",
    "Master Bedroom",
    "Bedroom",
    "Kids Room",
    "Guest Room",
    "Teen Room",
    "Kitchen",
    "Modular Kitchen",
    "Open Kitchen",
    "Pantry",
    "Dry Kitchen",
    "Wet Kitchen",
    "Master Bathroom",
    "Bathroom",
    "Powder Room",
    "Washroom",
    "Home Office",
    "Study Room",
    "Library Room",
    "Reading Nook",
    "Home Theatre",
    "Game Room",
    "Music Room",
    "Bar Room",
    "Hobby Room",
    "Home Gym",
    "Yoga Room",
    "Meditation Room",
    "Spa Room",
    "Sauna Room",
    "Wardrobe Room",
    "Walk-in Closet",
    "Laundry Room",
    "Storage Room",
    "Utility Room",
    "Linen Room",
    "Balcony",
    "Terrace",
    "Rooftop",
    "Garden",
    "Courtyard",
    "Patio",
    "Deck",
    "Verandah",
    "Sit Out",
    "Foyer",
    "Entrance Hall",
    "Corridor",
    "Hallway",
    "Staircase",
    "Mudroom",
    "Pooja Room",
    "Nalukettu Courtyard",
    "Thinnai",
    "Reception Area",
    "Waiting Lounge",
    "Meeting Room",
    "Conference Room",
    "Boardroom",
    "Open Work Area",
    "Cabin",
    "Pantry Area",
    "Server Room",
    "Break Room",
    "Shop Floor",
    "Trial Room",
    "Display Area",
    "Billing Counter",
    "Hotel Lobby",
    "Hotel Room",
    "Hotel Suite",
    "Restaurant Dining Area",
    "Restaurant Kitchen",
    "Bar Area",
    "Cafe Seating",
    "Banquet Hall",
    "Event Space",
    "Consultation Room",
    "Treatment Room",
    "Waiting Room",
    "Reception",
    "Salon Floor",
    "Gym Floor",
    "Changing Room",
    "Pool Area",
    "Basement",
    "Attic",
    "Garage",
    "Parking Area",
    "Other",
];

export const DESIGN_STYLE_AI = [
    "Modern",
    "Contemporary",
    "Minimalist",
    "Maximalist",
    "Mid-Century Modern",
    "Transitional",
    "Futuristic",
    "Biophilic",
    "Wabi Sabi",
    "Organic Modern",
    "Rustic",
    "Modern Farmhouse",
    "Coastal",
    "Tropical",
    "Scandinavian",
    "Japandi",
    "French Country",
    "Mediterranean",
    "Victorian",
    "Art Deco",
    "Art Nouveau",
    "Bauhaus",
    "Shabby Chic",
    "Hollywood Glam",
    "Grandmillennial",
    "Industrial",
    "Loft",
    "Steampunk",
    "Brutalist",
    "Bohemian",
    "Eclectic",
    "Global Fusion",
    "Vintage",
    "Retro",
    "Japanese",
    "Zen",
    "Balinese",
    "Korean Modern",
    "Kerala Traditional",
    "South Indian Traditional",
    "Rajasthani",
    "Mughal",
    "Indo Modern",
    "Indo Contemporary",
    "Colonial Indian",
    "Luxury",
    "Modern Luxury",
    "Quiet Luxury",
    "Hotel Chic",
    "Dark Academia",
    "Cottagecore",
    "Dopamine Decor",
    "Traditional",
    "Classic",
    "Craftsman",
];


export type OptionType = { label: string; value: string };
