name: Deploy Backend to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            export PATH=$PATH:/usr/bin:/usr/local/bin:$HOME/.nvm/versions/node/$(ls $HOME/.nvm/versions/node 2>/dev/null | tail -n 1)/bin

            cd /home/ubuntu/designo
            git fetch origin main
            git reset --hard origin/main


            cd /home/ubuntu/designo/backend
            npm install
            npm run build

            pm2 reload designo-backend || pm2 start dist/server.js --name "designo-backend"
            pm2 save